name: MLOps Pipeline Automation

on: [push]

jobs:
  notebook-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: iterative/setup-cml@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies explicitly
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert numpy pandas tensorflow scikit-learn matplotlib shap h2o optuna

      - name: List files for debugging
        run: ls -R

      - name: Execute notebook explicitly
        run: |
          jupyter nbconvert --to notebook --execute ./fashion_mnist_mlops_pipeline.ipynb --output executed_notebook.ipynb
